sudo: required
services:
  - docker
language: python
python:
  - "2.7"
before_install:
  - docker build -t lepidopter/integration --build-arg lepidopter_update_tag=$TRAVIS_COMMIT tests/integration
script:
  - make unittest
  - docker run lepidopter/integration
