sudo: required
services:
  - docker
language: python
python:
  - "2.7"
before_install:
  - docker build -t lepidopter/integration tests/integration
script:
  - make unittest
  - docker run lepidopter/integration
